/* eslint-disable */
// This file is automatically generated by Convex.
// To regenerate, run `npx convex dev`.

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
