-- Insert Ideas Data
-- Execute this in the Supabase SQL Editor after running schema.sql

INSERT INTO ideas (
  title, description, category, stage, potential_revenue, implementation_complexity, 
  time_to_market, required_skills, market_size, competition_level, ai_relevance, 
  hardware_component, related_income_stream, source_of_inspiration, next_steps, tags, 
  created_date, last_updated
) VALUES
(
  'AI-Powered Smart Building Assessment Platform',
  'SaaS platform that uses AI to analyze building plans and current infrastructure to recommend smart building upgrades with ROI projections and implementation roadmaps.',
  'B2B SaaS',
  'researching',
  'very-high',
  4,
  '8-12 months',
  ARRAY['AI/ML', 'Building systems', 'SaaS development', 'Computer vision'],
  '$15B smart building market',
  'medium',
  true,
  true,
  'is-001',
  'Client requests for smart building assessments in consulting work',
  ARRAY['Survey 50 building managers on pain points', 'Develop MVP assessment algorithm', 'Partner with IoT hardware vendors'],
  ARRAY['AI', 'Smart Buildings', 'SaaS', 'IoT', 'Enterprise'],
  '2024-02-15',
  '2024-12-01'
),
(
  'AI Newsletter Content Syndication Network',
  'Platform connecting AI newsletter creators with corporations needing curated AI content for internal communications and thought leadership.',
  'Content Platform',
  'validating',
  'high',
  3,
  '4-6 months',
  ARRAY['Content curation', 'Platform development', 'B2B sales'],
  '$8B content marketing market',
  'low',
  true,
  false,
  'is-003',
  'Corporate readers asking to license newsletter content',
  ARRAY['Interview 20 corporate content managers', 'Build pilot syndication system', 'Test with 3 newsletter creators'],
  ARRAY['AI', 'Content', 'B2B', 'Newsletter', 'Licensing'],
  '2024-03-10',
  '2024-11-28'
),
(
  'Hardware-Software Integration Certification Program',
  'Online certification program for developers and engineers specializing in IoT and hardware-software integration, with hands-on labs and industry partnerships.',
  'Education',
  'raw-thought',
  'medium',
  3,
  '6-9 months',
  ARRAY['Curriculum development', 'IoT expertise', 'Video production', 'Assessment design'],
  '$366B online education market',
  'medium',
  false,
  true,
  'is-007',
  'Lack of quality IoT integration training programs in market',
  ARRAY['Research competitor offerings', 'Design curriculum outline', 'Identify hardware lab partners'],
  ARRAY['Education', 'IoT', 'Certification', 'Hardware', 'Professional Development'],
  '2024-01-20',
  '2024-10-15'
),
(
  'AI Trend Prediction API for Businesses',
  'API service that analyzes social media, research papers, and industry data to predict emerging AI trends with confidence scores and business impact assessments.',
  'API Service',
  'developing',
  'high',
  5,
  '10-15 months',
  ARRAY['Machine learning', 'Data engineering', 'API development', 'Trend analysis'],
  '$50B business intelligence market',
  'medium',
  true,
  false,
  'is-006',
  'Newsletter research process revealing patterns in AI adoption',
  ARRAY['Build trend detection prototype', 'Validate with newsletter data', 'Interview potential enterprise customers'],
  ARRAY['AI', 'API', 'Prediction', 'Business Intelligence', 'Trends'],
  '2024-04-05',
  '2024-12-02'
),
(
  'Smart Office Space Design Consultation Bot',
  'AI-powered chatbot that provides instant office space design recommendations based on team size, work style, and technology requirements.',
  'AI Tool',
  'raw-thought',
  'medium',
  3,
  '5-7 months',
  ARRAY['Conversational AI', 'Office design knowledge', 'Chatbot development'],
  '$13B office design market',
  'low',
  true,
  false,
  'is-001',
  'Repetitive client questions about space optimization',
  ARRAY['Map common client questions', 'Research conversational AI platforms', 'Design conversation flow'],
  ARRAY['AI', 'Chatbot', 'Office Design', 'Consultation', 'Automation'],
  '2024-05-12',
  '2024-09-20'
),
(
  'Corporate AI Readiness Assessment Tool',
  'Comprehensive assessment platform that evaluates company readiness for AI implementation across technical, organizational, and strategic dimensions.',
  'Assessment Tool',
  'validating',
  'high',
  3,
  '4-6 months',
  ARRAY['AI strategy', 'Assessment design', 'Web development', 'Business analysis'],
  '$126B AI market',
  'medium',
  true,
  false,
  'is-009',
  'Corporate clients asking for AI implementation guidance',
  ARRAY['Complete assessment framework', 'Test with 5 pilot companies', 'Develop scoring algorithm'],
  ARRAY['AI', 'Assessment', 'Corporate', 'Strategy', 'Implementation'],
  '2024-02-28',
  '2024-11-30'
),
(
  'IoT Device Integration Marketplace',
  'Platform connecting IoT device manufacturers with system integrators, featuring compatibility testing, integration guides, and certified partnerships.',
  'Marketplace',
  'researching',
  'very-high',
  4,
  '12-18 months',
  ARRAY['Marketplace development', 'IoT protocols', 'Partner management', 'Testing frameworks'],
  '$300B IoT market',
  'medium',
  false,
  true,
  'is-007',
  'Difficulty finding compatible IoT solutions for client projects',
  ARRAY['Interview 30 IoT manufacturers', 'Survey system integrators', 'Research existing marketplaces'],
  ARRAY['IoT', 'Marketplace', 'Integration', 'Hardware', 'B2B'],
  '2024-06-18',
  '2024-11-15'
); 